Fixed react native dependency Issue
maniac-tech/react-native-expo-read-sms pull request #23
Opened 2023-02-21 14:03 UTC by akki251

Because the expo app crashes due to a dependency issue while building, the latest version of RN has been used to keep it in sync with the other versions.

2023-02-21 20:06 UTC, maniac-tech requested changes

2023-02-21 20:06 UTC, maniac-tech commented on package.json
> +  "author": "Abhishek Jain",
Remove the space character

2023-02-21 20:06 UTC, maniac-tech commented on package.json
> +    "react-native": "^0.70.5"
Have you reviewed and tested, if this impacts the functionality in anyway ?

2023-02-22 05:39 UTC, akki251 commented
Yes, after using this issue #24  arised, I think the major root cause of the library as of now is the react native versions!

2023-02-23 19:25 UTC, maniac-tech commented
Have bumped the peer dependency to 0.68.2 in #26 

Will check for impact within the same scope, that being said lets close this PR.

2023-02-26 05:04 UTC, closed without merging